### ISSUE TITLE
Domain sync script always fails on first domain

### ISSUE THREAD

**Issue by Bobones** [rendermani/ascio-whmcs-plugin#13]
I've noticed when running the WHMCS domainsync.php script that the 1st ASCIO domain always fails with ERROR: domain not found.

**Comment by pfrejo** [comment]
IMHO WHMCS default sync script isn't very reliable or suitable if you have a large domain portfolio. We use the polling/callback plugin feature and it's working pretty well. If you need any help you may contact ASCIO, I'm sure they'll be glad to help.

**Comment by rendermani** [comment]
i will close because outdated. Should be fixed. No current issues.
