### ISSUE TITLE
Error after upgrade to WHMCS 7.5 - PHP 7.2 - Ioncube 10.2.0

### ISSUE THREAD

**Issue by glardone** [rendermani/ascio-whmcs-plugin#16]
After the upgrade, I get this error:

[php7:notice] [pid 32755] [WHMCS Application] ERROR: ArgumentCountError: Too few arguments to function Request::searchDomain(), 0 passed in /public/modules/registrars/ascio/ascio.php on line 52 and exactly 1 expected in /public/modules/registrars/ascio/lib/Request.php:134 Stack trace: #0 /public/modules/registrars/ascio/ascio.php(52): Request->searchDomain() #1 /public/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): ascio_GetNameservers(Array) #2 /public/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\\Module\\AbstractModule->call('GetNameservers', Array) #3 /public/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\\Module\\Registrar->call('GetNameservers', Array) #4 /public/backend/clientsdomains.php(0): WHMCS\\Domains->moduleCall('GetNameservers') #5 {main} {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Request::searchDomain(), 0 passed in /public/modules/registrars/ascio/ascio.php on line 52 and exactly 1 expected at /public/modules/registrars/ascio/lib/Request.php:134)"}

**Comment by yapjackson** [comment]
Is this fixed for WHMCS 7.5?

**Comment by yapjackson** [comment]
if you have the workaround for this please let us know!

**Comment by itsrmcintosh** [comment]
I'm still waiting on a response here too, no automation means I need to pull the domains off of ascio..

**Comment by rendermani** [comment]
is compatible with whmcs 8.8
