### ISSUE TITLE
Few errors and Questions

### ISSUE THREAD

**Issue by jvalters** [rendermani/ascio-whmcs-plugin#20]
Hello, I was using the old Plugin, but now due to a change in some plans, I tried the new one. I have some problems and also some questions. 

1. Is it possible to automatically get Domains/TLDs names from ascio inside WHMCS ( /admin/configdomains.php )?
2. Is it possible to automatically get SSL certificates inside products?

Setting up the newest plugin I get: ( /admin/addonmodules.php?module=ascio ) 

_Addons
An Error Occurred. Please check module coding._
<img width="1049" alt="Screenshot 2021-12-05 at 13 00 25" src="https://user-images.githubusercontent.com/40427504/144743789-f00d052d-7cfb-4a0e-9ee2-e07ef0309a20.png">

Inside ( admin/configaddonmods.php ) It doesn't show module information:

<img width="1493" alt="Screenshot 2021-12-05 at 13 03 36" src="https://user-images.githubusercontent.com/40427504/144743871-65e4265c-9f31-4544-823e-2ba97df3f01a.png">

**Comment by rendermani** [comment]
1. The price-sync is integrated with the newest whmcs module interface. 
2. That is difficult, but there is an SSL module. Not sure how up-to-date it is.
