### ISSUE TITLE
issue with php 8.1

### ISSUE THREAD

**Issue by barianiluca** [rendermani/ascio-whmcs-plugin#21]
As asked by whmcs, we have updated the php version on the whmcs itself. Before php 7.4, now php 8.1
With php 8.1 i see few errors. Example:

```
 private function formatDate($xsDateTime) {
                if($xsDateTime == "0001-01-01T00:00:00") return false;
                $dateTokens = explode("T", $xsDateTime);
                if(count($dateTokens == 2)) {
                    return str_replace("-", "", $dateTokens[0]);
                }
                return false;
        }
```

here if $dateTokens is not an array, php 8.1 return a fatal error. And is no longer access to the domain page.
I have added a control over that array in order to temporary fix.
Please can you check if the rest of the implementation is php 8.1 ready?

ty

**Comment by barianiluca** [comment]
aside the array check, here there is also a syntax wrong on:

if(count($dateTokens == 2)) {

should be something like:

if(count($dateTokens) == 2) {

**Comment by barianiluca** [comment]
Another issue with php 8.1 is that one:

```
[Wed Jun 28 02:52:23.225661 2023] [fcgid:warn] [pid 15369:tid 139695794525952] [client 159.69.25.208:0] mod_fcgid: stderr: [WHMCS Application] ERROR: Error: Undefined constant "__PATH__" in /var/www/XXX/web/modules/registrars/ascio/callbacks.php:26 Stack trace: #0 {main} {"exception":"[object] (Error(code: 0): Undefined constant \\"__PATH__\\" at /var/www/XXX/web/modules/registrars/ascio/callbacks.php:26)"} []
```

In my opinion the variable assigned on that row 26 `$path = pathinfo(__PATH__);` is not used from the script and should be removed.

**Comment by barianiluca** [comment]
Another issue with php 8.1 is that one:

```
[Mon Jul 03 15:29:14.579993 2023] [fcgid:warn] [pid 17283:tid 139695659968256] [client 116.203.179.153:52326] mod_fcgid: stderr: [WHMCS Application] ERROR: Error: Attempt to assign property "domainId" on null in /path/to/web/modules/registrars/ascio/lib/Request.php:190 Stack trace: #0 /path/to/web/modules/registrars/ascio/ascio.php(168): Request->searchDomain() #1 [internal function]: ascio_GetNameservers() #2 /path/to/web/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func() #3 /path/to/web/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\\Module\\AbstractModule->call() #4 /path/to/web/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\\Module\\Registrar->call() #5 /path/to/web/vendor/whmcs/whmcs-foundation/lib/Domains.php(0): WHMCS\\Domains->moduleCall() #6 /path/to/web/go/clientsdomains.php(0): WHMCS\\Domains->getDomainInformation() #7 {main} {"exception":"[object] (Error(code: 0): Attempt to assign property \\"domainId\\" on null at /path/to/web/modules/registrars/ascio/lib/Request.php:190)"} [], referer: https://our-whmcs/go/
```

fixed with this:

```
File: .../modules/registrars/ascio/lib/Request.php
Row: 190

Added:
if (!is_object($result->domains->Domain)){return False; }

```

**Comment by barianiluca** [comment]
Another issue with php 8.1 is that one:

```
Error: TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in ../modules/registrars/ascio/lib/Request.php:111 Stack trace: #0 ../modules/registrars/ascio/lib/Request.php(83): Request->sendRequest() #1 ../modules/registrars/ascio/lib/Request.php(151): Request->request() #2 ../modules/registrars/ascio/lib/Request.php(256): Request->getDomain() #3 ../modules/registrars/ascio/polling.php(15): Request->getCallbackData() #4 {main}
```

probably fixed in that way:

```
//} else if (count($status->Values->string) > 1 ){
   } else if (is_countable($status->Values->string)){
           if (count($status->Values->string) > 1 ){
                   $messages = join(", \r\n",$status->Values->string);
           }
[...]
```

**Comment by barianiluca** [comment]
Another issue with php 8.1 is that one:

```
mod_fcgid: stderr: [WHMCS Application] ERROR: Error: Undefined constant "__PATH__" in /../registrars/ascio/callbacks.php:26 Stack trace: #0 {main} {"exception":"[object] (Error(code: 0): Undefined constant \\"__PATH__\\" at /../registrars/ascio/callbacks.php:26)"} []
```

that is probably a minor one, because:

```
$path = pathinfo(__PATH__);
```

the variable $path not seems to be used. btw i think that could be fixed as:

```
$path = pathinfo(__FILE__);
```

**Comment by barianiluca** [comment]
Also the `registrars/ascio/polling.php` does not work. But here without error, so can't fix it by myself.

**Comment by rendermani** [comment]
> count($dateToke

This looks ok in the current code

**Comment by rendermani** [comment]
> __PATH__

Your right, not used, removing it.

**Comment by rendermani** [comment]
> Another issue with php 8.1 is that one:
> 
> ```
> Error: TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in ../modules/registrars/ascio/lib/Request.php:111 Stack trace: #0 ../modules/registrars/ascio/lib/Request.php(83): Request->sendRequest() #1 ../modules/registrars/ascio/lib/Request.php(151): Request->request() #2 ../modules/registrars/ascio/lib/Request.php(256): Request->getDomain() #3 ../modules/registrars/ascio/polling.php(15): Request->getCallbackData() #4 {main}
> ```
> 
> probably fixed in that way:
> 
> ```
> //} else if (count($status->Values->string) > 1 ){
>    } else if (is_countable($status->Values->string)){
>            if (count($status->Values->string) > 1 ){
>                    $messages = join(", \r\n",$status->Values->string);
>            }
> [...]
> ```

This is already fixed. Thanks. Did it like this: 

is_array($status->Values->string) && count($status->Values->string) > 1 

both work

**Comment by rendermani** [comment]
> formatDate

The ascio api always returns an valid xsd:dateTime. But if you experience issues I can fix.
