### ISSUE TITLE
adding polling message id on the whmcs logs

### ISSUE THREAD

**Issue by barianiluca** [rendermani/ascio-whmcs-plugin#22]
Is it possible to add also on your main branch the message id of the polling on the whmcs logs?
I did something like this:

```
Tools::log("DomainId: " . $domainId." not found in the WHMCS-Database: " .$order->order->Type. ", Domain: ".$domainName.", Order-Status: ".$orderStatus."\n ".$errors.", Message-id: ".$messageId);
```

on row 253 of lib/Request.php

in order to see, faster, what is the message polling id that create problem. If any.
ty

**Comment by rendermani** [comment]
done
