### ISSUE TITLE
Separate out libphonenumber-for-PHP

### ISSUE THREAD

**Issue by gbxyz** [rendermani/ascio-whmcs-plugin#6]
Hi there,

I'm guessing that the libphonenumber-for-PHP subdirectory was created to solve the same problem that I have, namely that WHMCS doesn't present "clean" e164-formatted numbers required by EPP.

I'd like to avoid reinventing the wheel, and reuse your code in the CentralNic WHMCS module. There are a couple of things preventing that though:
1. the licensing status of this repository is unclear, I don't see a license file or anything in the README
2. would it be possible to create a separate Git repo for the libphonenumber-for-PHP subdirectory that I can add as a submodule?

Thanks!

**Comment by rendermani** [comment]
Hi Jodrell, 

1. You are right, the licensing is missing, I haven't decided which is the best yet. It should be opensource and free. Which License would you wish, I was thinking about LGPL. 

2. There are several repos for lib phonnumber: https://github.com/giggsey/libphonenumber-for-php. This is actually the google lib, and I thought it's very complete. It would be good to include it in a way that it is updated.

**Comment by jodrell** [comment]
I came across that repository after I submitted this issue. You could use it as a submodule of this repository, although it would change deployment slightly as you need to use git clone --recursive.

**Comment by rendermani** [comment]
I think I this is outdated and solved
